name: Build Kasm Wine Final

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Pull from Mirror
        run: |
          # 공식 저장소가 막혔을 때 사용하는 가장 확실한 미러 이미지입니다.
          docker pull malenurse/kasm-wine:latest
          
      - name: Save to Tar
        run: |
          # 이미지를 파일로 굽습니다.
          docker save -o kasm_wine.tar malenurse/kasm-wine:latest
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kasm-wine-image-file
          path: kasm_wine.tar
          retention-days: 1
